### ISSUE TITLE
Stop tracking VERSION file

### ISSUE THREAD

**Issue by dmiklic** [larics/assisi-python#64]
The file is autogenerated and should not be tracked. The way `create_package.py` currently works, it writes the current git commit hash to the file but then changes a tracked file (VERSION), thus creating a change to the wrt. to the commit it is referencing. The code still works correctly, but it is just wrong.

@rmm-fcul what's actually the purpose of this code in `create_package.py`:

```
# but first, ensure we are working with the repo version
VERSIONFILE=VERSION
#VERSIONFILE=/dev/null
if [ -f "${VERSIONFILE}" ] ; then
    git checkout -- ${VERSIONFILE}
else
    echo "[I] skipping cleanup"
fi
```

**Comment by rmm-fcul** [comment]
that part of the code is there because the older version appended the version info to the README which meant that if you ran it >1 time, multiple copies of the version info would go into the file.
However, if the VERSION file should only be a generated file for distribution bundles, I'll remove this code  and also remove the tracking of the file.
